# 第一階段
#FROM golang:1.26.1-alpine3.23 AS builder
FROM golang:1.26.1-alpine3.23 AS builder

RUN apk update && apk add --no-cache git

WORKDIR /app

#ENV GOPROXY=https://goproxy.io // go mod download 失敗請把註解拿掉

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o blackbox_agent

# 第二階段
FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata
ENV PATH="/venv/bin:$PATH" \
    TZ="Asia/Taipei"


WORKDIR /root/

COPY --from=builder /app/blackbox_agent .
COPY --from=builder /app/yaml ./yaml
COPY --from=builder /app/yaml/confignew.yaml ./yaml/config.yaml
COPY --from=builder /app/blackbox_exporter ./blackbox_exporter

EXPOSE 8080

CMD ["./blackbox_agent"]
