version: '3'
services:
  app:
    restart: always
    image: tonysystex/blackbox-agent:beta
    container_name: blackbox_agent
    logging:
      driver: "json-file"
      options:
        max-size: "3M"
        max-file: "3"
    volumes:
      - ./blackbox_exporter/blackbox.yaml:/root/blackbox_exporter/blackbox.yaml  # 挂载 blackbox.yaml 在本機目錄，確保重建容器時可以繼承上次的設定
      - ./yaml/target.yaml:/root/yaml/target.yaml  # 挂载 target.yaml在本機目錄，確保重建容器時可以繼承上次掃描Target的設定
        #
    environment:
      - RABBITMQ=10.40.192.80:5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin123
      - OPENSEARCH=https://10.11.233.101:9200
      - OPENSEARCH_USER=admin
      - OPENSEARCH_PASS=systex123!
      - OPENSEARCH_INDEX=discovery-index
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - PROMETHEUS_USERNAME=${PROMETHEUS_USERNAME} # Prometheus Basic Auth 的帳號不需要則填空字串
      - PROMETHEUS_PASSWORD=${PROMETHEUS_PASSWORD} # Prometheus Basic Auth 的密碼不需要則填空字串
      - PROMETHEUS_CERT=${PROMETHEUS_CERT} # 指向憑證存放的位置不需要則填空字串
      - INSECURETLS=${INSECURETLS} # 是否忽略tls驗證如果要忽略設定為true (true/false)

