#Opensearch 
opensearch:
  index: ${OPENSEARCH_INDEX} #opensearch index
  enable: false
  One:
    #    host: [${OPENSEARCH}]
    host: [${OPENSEARCH}]  # ["https://10.11.233.102:9200"]
    username: ${OPENSEARCH_USER}
    password: ${OPENSEARCH_PASS}

#RabbitMQ

rabbitMQ:
  One:
    host: [${RABBITMQ}] # RabbitMQ IP
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    RabbitMQExchange: "format" 
    RabbitMQRoutingKey: "format" 
    RabbitMQQueue: ["rpc-modules","rpc-scrape-configs"] 

#Prometheus
prometheus:
  prometheusUrl: ${PROMETHEUS_URL}
  username: ${PROMETHEUS_USERNAME}
  password: ${PROMETHEUS_PASSWORD}
  prometheusCert: ${PROMETHEUS_CERT}
  insecuretls: ${INSECURETLS}


#Const
const:
  httpRetrySecond: 5
  debug: false
  maxGoroutines: 500
  http_server_port: "8081"
