#Opensearch 
opensearch:
  index: ${OPENSEARCH_INDEX} #opensearch index
  enable: false
  One:
    #    host: [${OPENSEARCH}]
    host: [${OPENSEARCH}]  # ["https://10.11.233.102:9200"]
    username: ${OPENSEARCH_USER}
    password: ${OPENSEARCH_PASS}

#RabbitMQ

rabbitMQ:
  One:
    host: [${RABBITMQ}] # RabbitMQ IP
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    RabbitMQExchange: "format" 
    RabbitMQRoutingKey: "format" 
    RabbitMQQueue: ["rpc-modules","rpc-scrape-configs"] 

#Prometheus
prometheus:
  One:
    #host: ["http://10.11.233.10:9090/api/v1/write"]
    host: [${PROMETHEUS_URL}]
    enable: true


#Const
const:
  httpRetrySecond: 5
  debug: false
  maxGoroutines: 500
  http_server_port: "8081"
